/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true
    }
  },
  {
    name: 'about',
    path: '/about',
    component: 'layout.base$view.about',
    meta: {
      title: 'about',
      i18nKey: 'route.about',
      hideInMenu: true
    }
  },
  {
    name: 'function',
    path: '/function',
    component: 'layout.base',
    meta: {
      title: 'function',
      i18nKey: 'route.function',
      hideInMenu: true
    },
    children: [
      {
        name: 'function_hide-child',
        path: '/function/hide-child',
        meta: {
          title: 'function_hide-child',
          i18nKey: 'route.function_hide-child'
        },
        children: [
          {
            name: 'function_hide-child_one',
            path: '/function/hide-child/one',
            component: 'view.function_hide-child_one',
            meta: {
              title: 'function_hide-child_one',
              i18nKey: 'route.function_hide-child_one'
            }
          },
          {
            name: 'function_hide-child_three',
            path: '/function/hide-child/three',
            component: 'view.function_hide-child_three',
            meta: {
              title: 'function_hide-child_three',
              i18nKey: 'route.function_hide-child_three'
            }
          },
          {
            name: 'function_hide-child_two',
            path: '/function/hide-child/two',
            component: 'view.function_hide-child_two',
            meta: {
              title: 'function_hide-child_two',
              i18nKey: 'route.function_hide-child_two'
            }
          }
        ]
      },
      {
        name: 'function_multi-tab',
        path: '/function/multi-tab',
        component: 'view.function_multi-tab',
        meta: {
          title: 'function_multi-tab',
          i18nKey: 'route.function_multi-tab'
        }
      },
      {
        name: 'function_tab',
        path: '/function/tab',
        component: 'view.function_tab',
        meta: {
          title: 'function_tab',
          i18nKey: 'route.function_tab'
        }
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'inbox',
    path: '/inbox',
    component: 'layout.base$view.inbox',
    meta: {
      title: 'inbox',
      i18nKey: 'route.inbox',
      icon: 'mdi:store-cog-outline',
      order: 3
    }
  },
  {
    name: 'legal',
    path: '/legal',
    component: 'layout.base',
    meta: {
      title: 'legal',
      i18nKey: 'route.legal',
      icon: 'ic:baseline-gavel',
      order: 2
    },
    children: [
      {
        name: 'legal_giving-gifts',
        path: '/legal/giving-gifts',
        component: 'view.legal_giving-gifts',
        meta: {
          title: 'legal_giving-gifts',
          i18nKey: 'route.legal_giving-gifts',
          icon: 'mdi:cart-variant',
          order: 1
        }
      },
      {
        name: 'legal_giving-hospitality',
        path: '/legal/giving-hospitality',
        component: 'view.legal_giving-hospitality',
        meta: {
          title: 'legal_giving-hospitality',
          i18nKey: 'route.legal_giving-hospitality',
          icon: 'material-symbols-light:lunch-dining',
          order: 3
        }
      },
      {
        name: 'legal_receving-gifts',
        path: '/legal/receving-gifts',
        component: 'view.legal_receving-gifts',
        meta: {
          title: 'legal_receving-gifts',
          i18nKey: 'route.legal_receving-gifts',
          icon: 'material-symbols:text-select-move-back-word-outline',
          order: 2
        }
      },
      {
        name: 'legal_receving-hospitality',
        path: '/legal/receving-hospitality',
        component: 'view.legal_receving-hospitality',
        meta: {
          title: 'legal_receving-hospitality',
          i18nKey: 'route.legal_receving-hospitality',
          icon: 'mdi:hamburger-plus',
          order: 4,
          hideInMenu: true
        }
      }
    ]
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true
    }
  },
  {
    name: 'manage',
    path: '/manage',
    component: 'layout.base',
    meta: {
      title: 'manage',
      i18nKey: 'route.manage',
      icon: 'carbon:cloud-service-management',
      order: 4
    },
    children: [
      {
        name: 'manage_function',
        path: '/manage/function',
        component: 'view.manage_function',
        meta: {
          title: 'manage_function',
          i18nKey: 'route.manage_function',
          icon: 'material-symbols:format-indent-increase-rounded',
          order: 4
        }
      },
      {
        name: 'manage_group',
        path: '/manage/group',
        component: 'view.manage_group',
        meta: {
          title: 'manage_group',
          i18nKey: 'route.manage_group',
          icon: 'material-symbols:supervisor-account-outline-sharp',
          order: 3
        }
      },
      {
        name: 'manage_role',
        path: '/manage/role',
        component: 'view.manage_role',
        meta: {
          title: 'manage_role',
          i18nKey: 'route.manage_role',
          icon: 'carbon:user-role',
          order: 2
        }
      },
      {
        name: 'manage_route',
        path: '/manage/route',
        component: 'view.manage_route',
        meta: {
          title: 'manage_route',
          i18nKey: 'route.manage_route',
          hideInMenu: true
        }
      },
      {
        name: 'manage_user',
        path: '/manage/user',
        component: 'view.manage_user',
        meta: {
          title: 'manage_user',
          i18nKey: 'route.manage_user',
          icon: 'ic:round-manage-accounts',
          order: 1
        }
      },
      {
        name: 'manage_user-detail',
        path: '/manage/user-detail/:id',
        component: 'view.manage_user-detail',
        props: true,
        meta: {
          title: 'manage_user-detail',
          i18nKey: 'route.manage_user-detail',
          hideInMenu: true,
          activeMenu: 'manage_user'
        }
      }
    ]
  },
  {
    name: 'multi-menu',
    path: '/multi-menu',
    component: 'layout.base',
    meta: {
      title: 'multi-menu',
      i18nKey: 'route.multi-menu',
      hideInMenu: true
    },
    children: [
      {
        name: 'multi-menu_first',
        path: '/multi-menu/first',
        meta: {
          title: 'multi-menu_first',
          i18nKey: 'route.multi-menu_first'
        },
        children: [
          {
            name: 'multi-menu_first_child',
            path: '/multi-menu/first/child',
            component: 'view.multi-menu_first_child',
            meta: {
              title: 'multi-menu_first_child',
              i18nKey: 'route.multi-menu_first_child'
            }
          }
        ]
      },
      {
        name: 'multi-menu_second',
        path: '/multi-menu/second',
        meta: {
          title: 'multi-menu_second',
          i18nKey: 'route.multi-menu_second'
        },
        children: [
          {
            name: 'multi-menu_second_child',
            path: '/multi-menu/second/child',
            meta: {
              title: 'multi-menu_second_child',
              i18nKey: 'route.multi-menu_second_child'
            },
            children: [
              {
                name: 'multi-menu_second_child_home',
                path: '/multi-menu/second/child/home',
                component: 'view.multi-menu_second_child_home',
                meta: {
                  title: 'multi-menu_second_child_home',
                  i18nKey: 'route.multi-menu_second_child_home'
                }
              }
            ]
          }
        ]
      }
    ]
  },
  {
    name: 'user-center',
    path: '/user-center',
    component: 'layout.base$view.user-center',
    meta: {
      title: 'user-center',
      i18nKey: 'route.user-center',
      hideInMenu: true
    }
  }
];
